name: Build FlutterFlow APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install FlutterFlow CLI
        run: dart pub global activate flutterflow_cli

      - name: Download Code from FlutterFlow
        run: |
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          flutterflow export-code --project knight-noise-sw5s11 --dest . --no-include-assets --token ${{ secrets.FF_TOKEN }}

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
